import os, tempfile, pytest, logging, unittest
from werkzeug.security import check_password_hash, generate_password_hash

from App.main import create_app
from App.database import db, create_db
from App.models import *
from App.controllers import *


LOGGER = logging.getLogger(__name__)

'''
   Unit Tests
'''
class UnitTests(unittest.TestCase):

    #Team Unit Tests
    def test_new_team(self):
        app = create_app()  # Initialize the Flask app
        with app.app_context():  # Push the application context
            db.drop_all()
            db.create_all()

            # Create a new CompetitionTeam instance
            team = CompetitionTeam(comp_id=1, name="Scrum Lords")

            # Add the team to the database and commit
            db.session.add(team)
            db.session.commit()

            # Assert that the team's attributes are set correctly
            assert team.name == "Scrum Lords"
            assert team.comp_id == 1
            assert team.hasResult is False  # Default value for hasResult

    def test_team_get_json(self):
        app = create_app()  # Initialize the Flask app
        with app.app_context():  # Push the application context
            db.drop_all()
            db.create_all()

            # Create a new CompetitionTeam instance
            team = CompetitionTeam(comp_id=1, name="Scrum Lords")

            # Add the team to the database and commit
            db.session.add(team)
            db.session.commit()

            # Expected JSON output
            expected_json = {
                "id": team.id,             # Auto-generated by the database
                "competition_id": 1,       # Provided comp_id
                "name": "Scrum Lords",     # Team name
                "result": [],              # Default empty list (no results yet)
                "members": [],             # Default empty list (no members yet)
            }

            # Assert that `get_json` returns the expected dictionary
            self.assertDictEqual(team.get_json(), expected_json)